name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: nightly

      - uses: leafo/gh-actions-lua@v9.1.0
        with:
          luaVersion: "5.1"

      - name: Install luarocks
        uses: leafo/gh-actions-luarocks@v4

      - name: Install node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: npm

      - name: Setup tools
        run: |
          luarocks install vusted

      - name: Run tests
        run: |
          npm ci
          npm run update
          npm run test

